ALTER TABLE FELHASZNALO DROP PRIMARY KEY
/

ALTER TABLE FELHASZNALO ADD UNIQUE (NEV)
/

ALTER TABLE FELHASZNALO ADD ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY
/

ALTER TABLE PDF_SABLON DROP PRIMARY KEY
/

ALTER TABLE PDF_SABLON ADD ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY
/

ALTER TABLE RENDSZER_PARAMETER DROP PRIMARY KEY
/

ALTER TABLE RENDSZER_PARAMETER ADD ID INT AUTO_INCREMENT NOT NULL PRIMARY KEY
/