CREATE TABLE KIVETELNAP_TMP
  (
    ID									INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DATUM								DATE UNIQUE,
    TIPUS								VARCHAR(30) NOT NULL
  )
/

INSERT INTO KIVETELNAP_TMP (ID, DATUM, TIPUS) SELECT ID, STR_TO_DATE(CONCAT_WS(',', DATUM_NAP, DATUM_HO, DATUM_EV), '%d,%m,%Y'), TIPUS FROM KIVETELNAP
/

DROP TABLE KIVETELNAP
/

CREATE TABLE KIVETELNAP
  (
    ID									INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DATUM								DATE UNIQUE,
    TIPUS								VARCHAR(30) NOT NULL
  )
/

INSERT INTO KIVETELNAP (ID, DATUM, TIPUS) SELECT ID, DATUM, TIPUS FROM KIVETELNAP_TMP
/

DROP TABLE KIVETELNAP_TMP
/