ALTER TABLE MUNKAKORI_HISTORIKUS_ADAT ADD DATUM DATE
/

UPDATE MUNKAKORI_HISTORIKUS_ADAT SET DATUM = STR_TO_DATE(CONCAT_WS(',', NAP, HO, EV), '%e,%m,%Y') WHERE NAP != -1
/

ALTER TABLE MUNKAKORI_HISTORIKUS_ADAT DROP COLUMN NAP
/

ALTER TABLE MUNKAKORI_HISTORIKUS_ADAT DROP COLUMN HO
/

ALTER TABLE MUNKAKORI_HISTORIKUS_ADAT DROP COLUMN EV
/