ALTER TABLE KEPZETTSEG ADD ERVENYESSEG_VEGE DATE
/

UPDATE KEPZETTSEG SET ERVENYESSEG_VEGE = STR_TO_DATE(CONCAT_WS(',', ERVENYESSEG_VEGE_NAP, ERVENYESSEG_VEGE_HO, ERVENYESSEG_VEGE_EV), '%e,%m,%Y') WHERE ERVENYESSEG_VEGE_NAP != -1
/

ALTER TABLE KEPZETTSEG DROP COLUMN ERVENYESSEG_VEGE_NAP
/

ALTER TABLE KEPZETTSEG DROP COLUMN ERVENYESSEG_VEGE_HO
/

ALTER TABLE KEPZETTSEG DROP COLUMN ERVENYESSEG_VEGE_EV
/

ALTER TABLE KEPZETTSEG ADD EV_2 DATE
/

UPDATE KEPZETTSEG SET EV_2 = STR_TO_DATE(CONCAT_WS(',', '01', '01', EV), '%e,%m,%Y') WHERE EV != -1
/

ALTER TABLE KEPZETTSEG DROP COLUMN EV
/

ALTER TABLE KEPZETTSEG ADD EV DATE
/

UPDATE KEPZETTSEG SET EV = EV_2
/

ALTER TABLE KEPZETTSEG DROP COLUMN EV_2
/