ALTER TABLE CSALADTAG ADD SZULETESI_DATUM DATE
/

UPDATE CSALADTAG SET SZULETESI_DATUM = STR_TO_DATE(CONCAT_WS(',', SZULETESI_NAP, SZULETESI_HO, SZULETESI_EV), '%e,%m,%Y')
/

ALTER TABLE CSALADTAG DROP COLUMN SZULETESI_NAP
/

ALTER TABLE CSALADTAG DROP COLUMN SZULETESI_HO
/

ALTER TABLE CSALADTAG DROP COLUMN SZULETESI_EV
/