ALTER TABLE SZEMELYITORZS ADD UTOLSO_ORVOSI_VIZSGALAT_IDOPONTJA DATE
/

UPDATE SZEMELYITORZS SET UTOLSO_ORVOSI_VIZSGALAT_IDOPONTJA = STR_TO_DATE(CONCAT_WS(',', UTOLSO_ORVOSI_VIZSGALAT_IDOPONTJA_NAP, UTOLSO_ORVOSI_VIZSGALAT_IDOPONTJA_HO, UTOLSO_ORVOSI_VIZSGALAT_IDOPONTJA_EV), '%e,%m,%Y') WHERE UTOLSO_ORVOSI_VIZSGALAT_IDOPONTJA_NAP != -1
/

ALTER TABLE SZEMELYITORZS DROP COLUMN UTOLSO_ORVOSI_VIZSGALAT_IDOPONTJA_NAP
/

ALTER TABLE SZEMELYITORZS DROP COLUMN UTOLSO_ORVOSI_VIZSGALAT_IDOPONTJA_HO
/

ALTER TABLE SZEMELYITORZS DROP COLUMN UTOLSO_ORVOSI_VIZSGALAT_IDOPONTJA_EV
/