CREATE TABLE JELENLETI_ADAT2
  (
    ID									INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SZEMELYITORZS			 			INT NOT NULL,
    DATUM								DATE NOT NULL,
    TIPUS								VARCHAR(30) NOT NULL,
    KEZDET								TIME,
    VEG									TIME,
    LEDOLGOZOTT							TIME,
    TO50								TIME,
    TO100								TIME,
    M30									TIME
  )
/

ALTER TABLE JELENLETI_ADAT2 ADD UNIQUE INDEX(SZEMELYITORZS, DATUM)
/

ALTER TABLE JELENLETI_ADAT2 ADD FOREIGN KEY (SZEMELYITORZS) REFERENCES SZEMELYITORZS(TSZ)
/

INSERT INTO JELENLETI_ADAT2 (ID, SZEMELYITORZS, DATUM, TIPUS, KEZDET, VEG, LEDOLGOZOTT, TO50, TO100, M30) SELECT ID, SZEMELYITORZS, STR_TO_DATE(CONCAT_WS(',', NAP, HO, EV), '%e,%m,%Y'), TIPUS, STR_TO_DATE(CONCAT_WS(',', KEZDET_ORA, KEZDET_PERC), '%H,%i'), STR_TO_DATE(CONCAT_WS(',', VEG_ORA, VEG_PERC), '%H,%i'), STR_TO_DATE(CONCAT_WS(',', LEDOLGOZOTT_ORA, LEDOLGOZOTT_PERC), '%H,%i'), STR_TO_DATE(CONCAT_WS(',', TO50_ORA, TO50_PERC), '%H,%i'), STR_TO_DATE(CONCAT_WS(',', TO100_ORA, TO100_PERC), '%H,%i'), STR_TO_DATE(CONCAT_WS(',', M30_ORA, M30_PERC), '%H,%i') FROM JELENLETI_ADAT
/

DROP TABLE JELENLETI_ADAT CASCADE
/

CREATE TABLE JELENLETI_ADAT
  (
    ID									INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SZEMELYITORZS			 			INT NOT NULL,
    DATUM								DATE NOT NULL,
    TIPUS								VARCHAR(30) NOT NULL,
    KEZDET								TIME,
    VEG									TIME,
    LEDOLGOZOTT							TIME,
    TO50								TIME,
    TO100								TIME,
    M30									TIME
  )
/

ALTER TABLE JELENLETI_ADAT ADD UNIQUE INDEX(SZEMELYITORZS, DATUM)
/

ALTER TABLE JELENLETI_ADAT ADD FOREIGN KEY (SZEMELYITORZS) REFERENCES SZEMELYITORZS(TSZ)
/

INSERT INTO JELENLETI_ADAT (ID, SZEMELYITORZS, DATUM, TIPUS, KEZDET, VEG, LEDOLGOZOTT, TO50, TO100, M30) SELECT ID, SZEMELYITORZS, DATUM, TIPUS, KEZDET, VEG, LEDOLGOZOTT, TO50, TO100, M30 FROM JELENLETI_ADAT2
/

DROP TABLE JELENLETI_ADAT2 CASCADE
/