ALTER TABLE FELHASZNALO ADD COLUMN LOCALE VARCHAR(5)
/

UPDATE FELHASZNALO SET LOCALE = 'hu_HU'
/

ALTER TABLE FELHASZNALO MODIFY LOCALE VARCHAR(5) NOT NULL
/

CREATE TABLE LOCALES
  (
    LOCALE			VARCHAR(5) NOT NULL PRIMARY KEY
  )
/

INSERT INTO LOCALES (LOCALE) VALUES('hu_HU')
/

INSERT INTO LOCALES (LOCALE) VALUES('en_US')
/

ALTER TABLE FELHASZNALO ADD CONSTRAINT FK_LOCALE FOREIGN KEY (LOCALE) REFERENCES LOCALES(LOCALE)
/