ALTER TABLE FELHASZNALO DROP PRIMARY KEY
/

ALTER TABLE FELHASZNALO ADD UNIQUE (NEV)
/

ALTER TABLE FELHASZNALO ADD COLUMN ID INT AUTO_INCREMENT NOT NULL
/

ALTER TABLE FELHASZNALO ADD PRIMARY KEY (ID)
/

ALTER TABLE PDF_SABLON DROP PRIMARY KEY
/

ALTER TABLE PDF_SABLON ADD COLUMN ID INT AUTO_INCREMENT NOT NULL
/

ALTER TABLE PDF_SABLON ADD PRIMARY KEY (ID)
/

ALTER TABLE RENDSZER_PARAMETER DROP PRIMARY KEY
/

ALTER TABLE RENDSZER_PARAMETER ADD COLUMN ID INT AUTO_INCREMENT NOT NULL
/

ALTER TABLE RENDSZER_PARAMETER ADD PRIMARY KEY (ID)
/
