ALTER TABLE SZEMELYITORZS ADD SZULETESI_DATUM DATE
/

UPDATE SZEMELYITORZS SET SZULETESI_DATUM = PARSEDATETIME(CONCAT_WS('-', SZULETESI_NAP, SZULETESI_HO, SZULETESI_EV), 'dd-MM-yyyy') WHERE SZULETESI_NAP != -1
/

ALTER TABLE SZEMELYITORZS DROP COLUMN SZULETESI_NAP
/

ALTER TABLE SZEMELYITORZS DROP COLUMN SZULETESI_HO
/

ALTER TABLE SZEMELYITORZS DROP COLUMN SZULETESI_EV
/

ALTER TABLE SZEMELYITORZS ADD SZEMELYI_IGAZOLVANY_SZAM_LEJARAT DATE
/

UPDATE SZEMELYITORZS SET SZEMELYI_IGAZOLVANY_SZAM_LEJARAT = PARSEDATETIME(CONCAT_WS('-', SZEMELYI_IGAZOLVANY_SZAM_LEJARAT_NAP, SZEMELYI_IGAZOLVANY_SZAM_LEJARAT_HO, SZEMELYI_IGAZOLVANY_SZAM_LEJARAT_EV), 'dd-MM-yyyy') WHERE SZEMELYI_IGAZOLVANY_SZAM_LEJARAT_NAP != -1
/

ALTER TABLE SZEMELYITORZS DROP COLUMN SZEMELYI_IGAZOLVANY_SZAM_LEJARAT_NAP
/

ALTER TABLE SZEMELYITORZS DROP COLUMN SZEMELYI_IGAZOLVANY_SZAM_LEJARAT_HO
/

ALTER TABLE SZEMELYITORZS DROP COLUMN SZEMELYI_IGAZOLVANY_SZAM_LEJARAT_EV
/

ALTER TABLE SZEMELYITORZS ADD UTLEVEL_SZAM_LEJARAT DATE
/

UPDATE SZEMELYITORZS SET UTLEVEL_SZAM_LEJARAT = PARSEDATETIME(CONCAT_WS('-', UTLEVEL_SZAM_LEJARAT_NAP, UTLEVEL_SZAM_LEJARAT_HO, UTLEVEL_SZAM_LEJARAT_EV), 'dd-MM-yyyy') WHERE UTLEVEL_SZAM_LEJARAT_NAP != -1
/

ALTER TABLE SZEMELYITORZS DROP COLUMN UTLEVEL_SZAM_LEJARAT_NAP
/

ALTER TABLE SZEMELYITORZS DROP COLUMN UTLEVEL_SZAM_LEJARAT_HO
/

ALTER TABLE SZEMELYITORZS DROP COLUMN UTLEVEL_SZAM_LEJARAT_EV
/

ALTER TABLE SZEMELYITORZS ADD JOGOSITVANY_SZAM_LEJARAT DATE
/

UPDATE SZEMELYITORZS SET JOGOSITVANY_SZAM_LEJARAT = PARSEDATETIME(CONCAT_WS('-', JOGOSITVANY_SZAM_LEJARAT_NAP, JOGOSITVANY_SZAM_LEJARAT_HO, JOGOSITVANY_SZAM_LEJARAT_EV), 'dd-MM-yyyy') WHERE JOGOSITVANY_SZAM_LEJARAT_NAP != -1
/

ALTER TABLE SZEMELYITORZS DROP COLUMN JOGOSITVANY_SZAM_LEJARAT_NAP
/

ALTER TABLE SZEMELYITORZS DROP COLUMN JOGOSITVANY_SZAM_LEJARAT_HO
/

ALTER TABLE SZEMELYITORZS DROP COLUMN JOGOSITVANY_SZAM_LEJARAT_EV
/
