ALTER TABLE SZEMELYITORZS ADD JOGVISZONY_KEZDETE DATE
/

UPDATE SZEMELYITORZS SET JOGVISZONY_KEZDETE = PARSEDATETIME(CONCAT_WS('-', JOGVISZONY_KEZDETE_NAP, JOGVISZONY_KEZDETE_HO, JOGVISZONY_KEZDETE_EV), 'dd-MM-yyyy') WHERE JOGVISZONY_KEZDETE_NAP != -1
/

ALTER TABLE SZEMELYITORZS DROP COLUMN JOGVISZONY_KEZDETE_NAP
/

ALTER TABLE SZEMELYITORZS DROP COLUMN JOGVISZONY_KEZDETE_HO
/

ALTER TABLE SZEMELYITORZS DROP COLUMN JOGVISZONY_KEZDETE_EV
/

ALTER TABLE SZEMELYITORZS ADD JOGVISZONY_VEGE DATE
/

UPDATE SZEMELYITORZS SET JOGVISZONY_VEGE = PARSEDATETIME(CONCAT_WS('-', JOGVISZONY_VEGE_NAP, JOGVISZONY_VEGE_HO, JOGVISZONY_VEGE_EV), 'dd-MM-yyyy') WHERE JOGVISZONY_VEGE_NAP != -1
/

ALTER TABLE SZEMELYITORZS DROP COLUMN JOGVISZONY_VEGE_NAP
/

ALTER TABLE SZEMELYITORZS DROP COLUMN JOGVISZONY_VEGE_HO
/

ALTER TABLE SZEMELYITORZS DROP COLUMN JOGVISZONY_VEGE_EV
/

ALTER TABLE SZEMELYITORZS ADD PROBAIDO_VEGE DATE
/

UPDATE SZEMELYITORZS SET PROBAIDO_VEGE = PARSEDATETIME(CONCAT_WS('-', PROBAIDO_VEGE_NAP, PROBAIDO_VEGE_HO, PROBAIDO_VEGE_EV), 'dd-MM-yyyy') WHERE PROBAIDO_VEGE_NAP != -1
/

ALTER TABLE SZEMELYITORZS DROP COLUMN PROBAIDO_VEGE_NAP
/

ALTER TABLE SZEMELYITORZS DROP COLUMN PROBAIDO_VEGE_HO
/

ALTER TABLE SZEMELYITORZS DROP COLUMN PROBAIDO_VEGE_EV
/

ALTER TABLE SZEMELYITORZS ADD MUNKASZERZODES_LEJAR DATE
/

UPDATE SZEMELYITORZS SET MUNKASZERZODES_LEJAR = PARSEDATETIME(CONCAT_WS('-', MUNKASZERZODES_LEJAR_NAP, MUNKASZERZODES_LEJAR_HO, MUNKASZERZODES_LEJAR_EV), 'dd-MM-yyyy') WHERE MUNKASZERZODES_LEJAR_NAP != -1
/

ALTER TABLE SZEMELYITORZS DROP COLUMN MUNKASZERZODES_LEJAR_NAP
/

ALTER TABLE SZEMELYITORZS DROP COLUMN MUNKASZERZODES_LEJAR_HO
/

ALTER TABLE SZEMELYITORZS DROP COLUMN MUNKASZERZODES_LEJAR_EV
/