ALTER TABLE CSALADTAG ADD SZULETESI_DATUM DATE
/

UPDATE CSALADTAG SET SZULETESI_DATUM = PARSEDATETIME(CONCAT_WS('-', SZULETESI_NAP, SZULETESI_HO, SZULETESI_EV), 'dd-MM-yyyy')
/

ALTER TABLE CSALADTAG DROP COLUMN SZULETESI_NAP
/

ALTER TABLE CSALADTAG DROP COLUMN SZULETESI_HO
/

ALTER TABLE CSALADTAG DROP COLUMN SZULETESI_EV
/