CREATE TABLE SZABADSAG2
  (
    ID									INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SZEMELYITORZS			 			INT NOT NULL,
	DATUM								DATE NOT NULL,
    JELLEG		  						VARCHAR(30) NOT NULL
  )
/

ALTER TABLE SZABADSAG2 ADD UNIQUE INDEX(SZEMELYITORZS, DATUM)
/

ALTER TABLE SZABADSAG2 ADD FOREIGN KEY (SZEMELYITORZS) REFERENCES SZEMELYITORZS(TSZ)
/

INSERT INTO SZABADSAG2 (ID, SZEMELYITORZS, DATUM, JELLEG) SELECT ID, SZEMELYITORZS, PARSEDATETIME(CONCAT_WS('-', NAP, HO, EV), 'dd-MM-yyyy'), JELLEG FROM SZABADSAG
/

DROP TABLE SZABADSAG CASCADE
/

CREATE TABLE SZABADSAG
  (
    ID									INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SZEMELYITORZS			 			INT NOT NULL,
	DATUM								DATE NOT NULL,
    JELLEG		  						VARCHAR(30) NOT NULL
  )
/

ALTER TABLE SZABADSAG ADD UNIQUE INDEX(SZEMELYITORZS, DATUM)
/

ALTER TABLE SZABADSAG ADD FOREIGN KEY (SZEMELYITORZS) REFERENCES SZEMELYITORZS(TSZ)
/

INSERT INTO SZABADSAG (ID, SZEMELYITORZS, DATUM, JELLEG) SELECT ID, SZEMELYITORZS, DATUM, JELLEG FROM SZABADSAG2
/

DROP TABLE SZABADSAG2 CASCADE
/