ALTER TABLE FELHASZNALO ADD COLUMN LOCALE VARCHAR(5)
/

UPDATE FELHASZNALO SET LOCALE = 'hu_HU'
/

ALTER TABLE FELHASZNALO ALTER COLUMN LOCALE VARCHAR(5) NOT NULL
/

CREATE TABLE LOCALES
  (
    LOCALE			VARCHAR(5) NOT NULL PRIMARY KEY
  )
/

INSERT INTO LOCALES (LOCALE) VALUES('hu_HU')
/

INSERT INTO LOCALES (LOCALE) VALUES('en_US')
/

ALTER TABLE FELHASZNALO ADD FOREIGN KEY (LOCALE) REFERENCES LOCALES(LOCALE)
/