package hu.interconnect.hr.backend.api.enumeration;

public enum EmailTemplateType {
	IDENTIFICATION_QUALIFICATION_EXPIRES,
	EMPLOYMENT_RELATION_EXPIRES,
	MEDICAL_EXAMINATION_EXPIRES,
	PROBATIONARY_PERIOD_EXPIRES;
}
