CREATE TABLE RENDSZER_PARAMETER  (
   TIPUS		VARCHAR(30) NOT NULL PRIMARY KEY,
   ERTEK		VARCHAR(255)
)
/

INSERT INTO RENDSZER_PARAMETER(TIPUS, ERTEK) VALUES('KEPTARHELY', 'C:/HR/KEPEK/')
/

INSERT INTO RENDSZER_PARAMETER(TIPUS, ERTEK) VALUES('CSATOLMANYTARHELY', 'C:/HR/CSATOLMANYOK/')
/

INSERT INTO RENDSZER_PARAMETER(TIPUS, ERTEK) VALUES('FTP_SMS_HOSZT', '127.0.0.1')
/

INSERT INTO RENDSZER_PARAMETER(TIPUS, ERTEK) VALUES('FTP_SMS_PORT', '2221')
/

INSERT INTO RENDSZER_PARAMETER(TIPUS, ERTEK) VALUES('FTP_SMS_FELHASZNALONEV', 'felhasznalonev')
/

INSERT INTO RENDSZER_PARAMETER(TIPUS, ERTEK) VALUES('FTP_SMS_JELSZO', 'jelszo')
/

INSERT INTO RENDSZER_PARAMETER(TIPUS, ERTEK) VALUES('ADMIN_CC_EMAILCIMEK', 'Szilvia.Ulmer@videochat.vc;peter.veres@videochat.vc')
/

INSERT INTO RENDSZER_PARAMETER(TIPUS, ERTEK) VALUES('ADMIN_BCC_EMAILCIMEK', 'tornai.andras.ede@gmail.com')
/