CREATE TABLE CSALADTAG
  (
    ID									INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SZEMELYITORZS		 				INT NOT NULL,
    NEV									VARCHAR(255) NOT NULL,
    SZULETESI_EV						INT NOT NULL DEFAULT -1,
    SZULETESI_HO						INT NOT NULL DEFAULT -1,
    SZULETESI_NAP						INT NOT NULL DEFAULT -1,
    TAJ									VARCHAR(255),
    MEGJEGYZES							VARCHAR(255)
  )
/

ALTER TABLE CSALADTAG ADD FOREIGN KEY (SZEMELYITORZS) REFERENCES SZEMELYITORZS(TSZ)
/