CREATE TABLE KIVETELNAP
  (
    ID									INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DATUM_EV							INT NOT NULL DEFAULT -1,
    DATUM_HO							INT NOT NULL DEFAULT -1,
    DATUM_NAP							INT NOT NULL DEFAULT -1,
    TIPUS								VARCHAR(30) NOT NULL
  )
/

ALTER TABLE KIVETELNAP ADD UNIQUE INDEX (DATUM_EV, DATUM_HO, DATUM_NAP)
/

INSERT INTO KIVETELNAP(DATUM_EV, DATUM_HO, DATUM_NAP, TIPUS) VALUES (2012, 3, 16, 'PIHENONAP')
/

INSERT INTO KIVETELNAP(DATUM_EV, DATUM_HO, DATUM_NAP, TIPUS) VALUES (2012, 3, 24, 'MUNKANAP')
/

INSERT INTO KIVETELNAP(DATUM_EV, DATUM_HO, DATUM_NAP, TIPUS) VALUES (2012, 4, 21, 'MUNKANAP')
/

INSERT INTO KIVETELNAP(DATUM_EV, DATUM_HO, DATUM_NAP, TIPUS) VALUES (2012, 4, 30, 'PIHENONAP')
/

INSERT INTO KIVETELNAP(DATUM_EV, DATUM_HO, DATUM_NAP, TIPUS) VALUES (2012, 10, 22, 'PIHENONAP')
/

INSERT INTO KIVETELNAP(DATUM_EV, DATUM_HO, DATUM_NAP, TIPUS) VALUES (2012, 10, 27, 'MUNKANAP')
/

INSERT INTO KIVETELNAP(DATUM_EV, DATUM_HO, DATUM_NAP, TIPUS) VALUES (2012, 11, 2, 'PIHENONAP')
/

INSERT INTO KIVETELNAP(DATUM_EV, DATUM_HO, DATUM_NAP, TIPUS) VALUES (2012, 11, 10, 'MUNKANAP')
/

INSERT INTO KIVETELNAP(DATUM_EV, DATUM_HO, DATUM_NAP, TIPUS) VALUES (2012, 12, 1, 'MUNKANAP')
/

INSERT INTO KIVETELNAP(DATUM_EV, DATUM_HO, DATUM_NAP, TIPUS) VALUES (2012, 12, 15, 'MUNKANAP')
/

INSERT INTO KIVETELNAP(DATUM_EV, DATUM_HO, DATUM_NAP, TIPUS) VALUES (2012, 12, 24, 'PIHENONAP')
/

INSERT INTO KIVETELNAP(DATUM_EV, DATUM_HO, DATUM_NAP, TIPUS) VALUES (2012, 12, 31, 'PIHENONAP')
/

INSERT INTO KIVETELNAP(DATUM_EV, DATUM_HO, DATUM_NAP, TIPUS) VALUES (2013, 1, 1, 'PIHENONAP')
/

INSERT INTO KIVETELNAP(DATUM_EV, DATUM_HO, DATUM_NAP, TIPUS) VALUES (2013, 3, 15, 'PIHENONAP')
/

INSERT INTO KIVETELNAP(DATUM_EV, DATUM_HO, DATUM_NAP, TIPUS) VALUES (2013, 4, 1, 'PIHENONAP')
/

INSERT INTO KIVETELNAP(DATUM_EV, DATUM_HO, DATUM_NAP, TIPUS) VALUES (2013, 5, 1, 'PIHENONAP')
/

INSERT INTO KIVETELNAP(DATUM_EV, DATUM_HO, DATUM_NAP, TIPUS) VALUES (2013, 5, 20, 'PIHENONAP')
/

INSERT INTO KIVETELNAP(DATUM_EV, DATUM_HO, DATUM_NAP, TIPUS) VALUES (2013, 8, 19, 'PIHENONAP')
/

INSERT INTO KIVETELNAP(DATUM_EV, DATUM_HO, DATUM_NAP, TIPUS) VALUES (2013, 8, 20, 'PIHENONAP')
/

INSERT INTO KIVETELNAP(DATUM_EV, DATUM_HO, DATUM_NAP, TIPUS) VALUES (2013, 8, 24, 'MUNKANAP')
/

INSERT INTO KIVETELNAP(DATUM_EV, DATUM_HO, DATUM_NAP, TIPUS) VALUES (2013, 10, 23, 'PIHENONAP')
/

INSERT INTO KIVETELNAP(DATUM_EV, DATUM_HO, DATUM_NAP, TIPUS) VALUES (2013, 11, 1, 'PIHENONAP')
/

INSERT INTO KIVETELNAP(DATUM_EV, DATUM_HO, DATUM_NAP, TIPUS) VALUES (2013, 12, 7, 'MUNKANAP')
/

INSERT INTO KIVETELNAP(DATUM_EV, DATUM_HO, DATUM_NAP, TIPUS) VALUES (2013, 12, 21, 'MUNKANAP')
/

INSERT INTO KIVETELNAP(DATUM_EV, DATUM_HO, DATUM_NAP, TIPUS) VALUES (2013, 12, 24, 'PIHENONAP')
/

INSERT INTO KIVETELNAP(DATUM_EV, DATUM_HO, DATUM_NAP, TIPUS) VALUES (2013, 12, 25, 'PIHENONAP')
/

INSERT INTO KIVETELNAP(DATUM_EV, DATUM_HO, DATUM_NAP, TIPUS) VALUES (2013, 12, 26, 'PIHENONAP')
/

INSERT INTO KIVETELNAP(DATUM_EV, DATUM_HO, DATUM_NAP, TIPUS) VALUES (2013, 12, 27, 'PIHENONAP')
/