CREATE TABLE SZABADSAG
  (
    ID									INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SZEMELYITORZS			 			INT NOT NULL,
    EV									INT NOT NULL,
    HO									INT NOT NULL,
    NAP									INT NOT NULL,
    JELLEG		  						VARCHAR(30) NOT NULL
  )
/

ALTER TABLE SZABADSAG ADD UNIQUE INDEX(SZEMELYITORZS, EV, HO, NAP)
/

ALTER TABLE SZABADSAG ADD FOREIGN KEY (SZEMELYITORZS) REFERENCES SZEMELYITORZS(TSZ)
/