CREATE TABLE JELENLETI_ADAT
  (
    ID									INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SZEMELYITORZS			 			INT NOT NULL,
    EV									INT NOT NULL,
    HO									INT NOT NULL,
    NAP									INT NOT NULL,
    TIPUS								VARCHAR(30) NOT NULL,
    KEZDET_ORA							INT,
    KEZDET_PERC							INT,
    VEG_ORA								INT,
    VEG_PERC							INT,
    LEDOLGOZOTT_ORA						INT,
    LEDOLGOZOTT_PERC					INT,
    TO50_ORA							INT,
    TO50_PERC							INT,
    TO100_ORA							INT,
    TO100_PERC							INT,
    M30_ORA								INT,
    M30_PERC							INT
  )
/

ALTER TABLE JELENLETI_ADAT ADD UNIQUE INDEX(SZEMELYITORZS, EV, HO, NAP)
/

ALTER TABLE JELENLETI_ADAT ADD FOREIGN KEY (SZEMELYITORZS) REFERENCES SZEMELYITORZS(TSZ)
/