CREATE TABLE HAVI_JELENLETI_IV_ALLAPOT
  (
    ID									INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    EV									INT NOT NULL,
    HO									INT NOT NULL,
    SZERKESZTHETO						BOOLEAN NOT NULL
  )
/

ALTER TABLE HAVI_JELENLETI_IV_ALLAPOT ADD UNIQUE INDEX(EV, HO)
/