CREATE TABLE IDOZITETT_FUTTATAS
  (
	ID									INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	AZONOSITO							VARCHAR(255) NOT NULL,
    INDITAS_EV							INT NOT NULL DEFAULT -1,
    INDITAS_HO							INT NOT NULL DEFAULT -1,
    INDITAS_NAP							INT NOT NULL DEFAULT -1,
    INDITAS_ORA							INT NOT NULL DEFAULT -1,
    INDITAS_PERC						INT NOT NULL DEFAULT -1,
    INDITAS_MASODPERC					INT NOT NULL DEFAULT -1,
	BEFEJEZES_EV						INT NOT NULL DEFAULT -1,
	BEFEJEZES_HO						INT NOT NULL DEFAULT -1,
	BEFEJEZES_NAP						INT NOT NULL DEFAULT -1,
	BEFEJEZES_ORA						INT NOT NULL DEFAULT -1,
    BEFEJEZES_PERC						INT NOT NULL DEFAULT -1,
    BEFEJEZES_MASODPERC					INT NOT NULL DEFAULT -1,
	EREDMENY							LONGTEXT
  )
/

INSERT INTO IDOZITETT_FUTTATAS (AZONOSITO, INDITAS_EV, INDITAS_HO, INDITAS_NAP, INDITAS_ORA, INDITAS_PERC, INDITAS_MASODPERC, BEFEJEZES_EV, BEFEJEZES_HO, BEFEJEZES_NAP, BEFEJEZES_ORA, BEFEJEZES_PERC, BEFEJEZES_MASODPERC, EREDMENY) VALUES ('IgazolvanyKepzettsegLejarIdozitettFeladat', 2012, 3, 29, 18, 50, 1, 2012, 3, 29, 18, 50, 2, 'IgazolvanyKepzettsegLejarIdozitettFeladat - init')
/

INSERT INTO IDOZITETT_FUTTATAS (AZONOSITO, INDITAS_EV, INDITAS_HO, INDITAS_NAP, INDITAS_ORA, INDITAS_PERC, INDITAS_MASODPERC, BEFEJEZES_EV, BEFEJEZES_HO, BEFEJEZES_NAP, BEFEJEZES_ORA, BEFEJEZES_PERC, BEFEJEZES_MASODPERC, EREDMENY) VALUES ('JogviszonyVegeIdozitettFeladat', 2012, 3, 29, 18, 50, 3, 2012, 3, 29, 18, 50, 4, 'JogviszonyVegeIdozitettFeladat - init')
/

INSERT INTO IDOZITETT_FUTTATAS (AZONOSITO, INDITAS_EV, INDITAS_HO, INDITAS_NAP, INDITAS_ORA, INDITAS_PERC, INDITAS_MASODPERC, BEFEJEZES_EV, BEFEJEZES_HO, BEFEJEZES_NAP, BEFEJEZES_ORA, BEFEJEZES_PERC, BEFEJEZES_MASODPERC, EREDMENY) VALUES ('OrvosiVizsgalatLejarEmailIdozitettFeladat', 2012, 3, 29, 18, 50, 5, 2012, 3, 29, 18, 50, 6, 'OrvosiVizsgalatLejarEmailIdozitettFeladat - init')
/

INSERT INTO IDOZITETT_FUTTATAS (AZONOSITO, INDITAS_EV, INDITAS_HO, INDITAS_NAP, INDITAS_ORA, INDITAS_PERC, INDITAS_MASODPERC, BEFEJEZES_EV, BEFEJEZES_HO, BEFEJEZES_NAP, BEFEJEZES_ORA, BEFEJEZES_PERC, BEFEJEZES_MASODPERC, EREDMENY) VALUES ('OrvosiVizsgalatLejarSMSIdozitettFeladat', 2012, 3, 29, 18, 50, 7, 2012, 3, 29, 18, 50, 8, 'OrvosiVizsgalatLejarSMSIdozitettFeladat - init')
/

INSERT INTO IDOZITETT_FUTTATAS (AZONOSITO, INDITAS_EV, INDITAS_HO, INDITAS_NAP, INDITAS_ORA, INDITAS_PERC, INDITAS_MASODPERC, BEFEJEZES_EV, BEFEJEZES_HO, BEFEJEZES_NAP, BEFEJEZES_ORA, BEFEJEZES_PERC, BEFEJEZES_MASODPERC, EREDMENY) VALUES ('ProbaidoLejarIdozitettFeladat', 2012, 3, 29, 18, 50, 9, 2012, 3, 29, 18, 50, 10, 'ProbaidoLejarIdozitettFeladat - init')
/