CREATE TABLE FELHASZNALO
  (
    NEV				VARCHAR(255) NOT NULL PRIMARY KEY,
    JELSZO			VARCHAR(255) NOT NULL,
    SZEREP			VARCHAR(30) NOT NULL,
    SZEMELYITORZS	INT,
    ENABLED			BOOLEAN NOT NULL
  )
/

-- admin///admin
INSERT INTO FELHASZNALO(NEV, JELSZO, SZEREP, SZEMELYITORZS, ENABLED) VALUES('admin', 'a40546cc4fd6a12572828bb803380888ad1bfdab', 'ADMINISTRATOR', NULL, TRUE)
/