CREATE TABLE ERTEKKESZLET_ELEM
  (
    ID           		INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    TIPUS    			VARCHAR(30),
    MEGNEVEZES_MAGYAR 	VARCHAR(255),
    MEGNEVEZES_ANGOL	VARCHAR(255)
  )
/

ALTER TABLE ERTEKKESZLET_ELEM
   ADD UNIQUE INDEX (TIPUS, MEGNEVEZES_MAGYAR)
/

ALTER TABLE ERTEKKESZLET_ELEM
   ADD UNIQUE INDEX (TIPUS, MEGNEVEZES_ANGOL)
/

-- ALLAMPOLGARSAG
INSERT INTO ERTEKKESZLET_ELEM(ID, TIPUS, MEGNEVEZES_MAGYAR, MEGNEVEZES_ANGOL) VALUES(1, 'ALLAMPOLGARSAG', 'Magyar', 'Hungarian')
/

INSERT INTO ERTEKKESZLET_ELEM(ID, TIPUS, MEGNEVEZES_MAGYAR, MEGNEVEZES_ANGOL) VALUES(2, 'ALLAMPOLGARSAG', 'Angol', 'English')
/

INSERT INTO ERTEKKESZLET_ELEM(ID, TIPUS, MEGNEVEZES_MAGYAR, MEGNEVEZES_ANGOL) VALUES(3, 'ALLAMPOLGARSAG', 'Német', 'German')
/

INSERT INTO ERTEKKESZLET_ELEM(ID, TIPUS, MEGNEVEZES_MAGYAR, MEGNEVEZES_ANGOL) VALUES(4, 'ALLAMPOLGARSAG', 'Szlovák', 'Slovak')
/

INSERT INTO ERTEKKESZLET_ELEM(ID, TIPUS, MEGNEVEZES_MAGYAR, MEGNEVEZES_ANGOL) VALUES(5, 'ALLAMPOLGARSAG', 'Spanyol', 'Spanish')
/

-- SZERVEZETI_EGYSEG
INSERT INTO ERTEKKESZLET_ELEM(ID, TIPUS, MEGNEVEZES_MAGYAR, MEGNEVEZES_ANGOL) VALUES(6, 'SZERVEZETI_EGYSEG', 'Adminisztráció - Biatorbágy', 'Administration - Biatorbagy')
/

INSERT INTO ERTEKKESZLET_ELEM(ID, TIPUS, MEGNEVEZES_MAGYAR, MEGNEVEZES_ANGOL) VALUES(7, 'SZERVEZETI_EGYSEG', 'Menedzsment - Bécs', 'Management - Vienna')
/

-- KOLTSEGHELY
INSERT INTO ERTEKKESZLET_ELEM(ID, TIPUS, MEGNEVEZES_MAGYAR, MEGNEVEZES_ANGOL) VALUES(10, 'KOLTSEGHELY', 'HR - Munkaügy', 'HR - Labor')
/

INSERT INTO ERTEKKESZLET_ELEM(ID, TIPUS, MEGNEVEZES_MAGYAR, MEGNEVEZES_ANGOL) VALUES(11, 'KOLTSEGHELY', 'Menedzsment - Sales', 'Management - Sales')
/

-- FOGLALKOZASI_VISZONY
INSERT INTO ERTEKKESZLET_ELEM(ID, TIPUS, MEGNEVEZES_MAGYAR, MEGNEVEZES_ANGOL) VALUES(12, 'FOGLALKOZASI_VISZONY', 'Alkalmazásban álló', 'Employed')
/

INSERT INTO ERTEKKESZLET_ELEM(ID, TIPUS, MEGNEVEZES_MAGYAR, MEGNEVEZES_ANGOL) VALUES(13, 'FOGLALKOZASI_VISZONY', 'Önálló, egyéni vállalkozó', 'Independent, Self-employed')
/

-- FOGLALKOZTATAS_JELLEGE
INSERT INTO ERTEKKESZLET_ELEM(ID, TIPUS, MEGNEVEZES_MAGYAR, MEGNEVEZES_ANGOL) VALUES(14, 'FOGLALKOZTATAS_JELLEGE', 'Teljes munkaidőben foglalkoztatva', 'Full-time employed')
/

INSERT INTO ERTEKKESZLET_ELEM(ID, TIPUS, MEGNEVEZES_MAGYAR, MEGNEVEZES_ANGOL) VALUES(15, 'FOGLALKOZTATAS_JELLEGE', 'Részmunkaidőben foglalkoztatva', 'Part-time employed')
/

-- FEOR
INSERT INTO ERTEKKESZLET_ELEM(ID, TIPUS, MEGNEVEZES_MAGYAR, MEGNEVEZES_ANGOL) VALUES(18, 'FEOR', 'Humánpolitikai adminisztrátor', 'Human Resources Administrator')
/

INSERT INTO ERTEKKESZLET_ELEM(ID, TIPUS, MEGNEVEZES_MAGYAR, MEGNEVEZES_ANGOL) VALUES(19, 'FEOR', 'Favágó', 'Lumberjack')
/

-- MUNKAKOR
INSERT INTO ERTEKKESZLET_ELEM(ID, TIPUS, MEGNEVEZES_MAGYAR, MEGNEVEZES_ANGOL) VALUES(20, 'MUNKAKOR', 'Személyi', 'Personal')
/

INSERT INTO ERTEKKESZLET_ELEM(ID, TIPUS, MEGNEVEZES_MAGYAR, MEGNEVEZES_ANGOL) VALUES(21, 'MUNKAKOR', 'Egyéb', 'Other')
/