CREATE TABLE FENYKEP
  (
    ID           						INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SZEMELYITORZS	 					INT NOT NULL,
    EREDETI_NEV 						VARCHAR(255) NOT NULL,
    MINIATUR							BOOLEAN NOT NULL
  )
/

ALTER TABLE FENYKEP ADD FOREIGN KEY (SZEMELYITORZS) REFERENCES SZEMELYITORZS(TSZ)
/