CREATE TABLE MUNKAKORI_HISTORIKUS_ADAT
  (
    ID									INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SZEMELYITORZS			 			INT NOT NULL,
    EV									INT NOT NULL,
    HO									INT NOT NULL,
    NAP									INT NOT NULL,
    FEOR		 						INT NOT NULL,
    FIZETES								INT NOT NULL
  )
/

ALTER TABLE MUNKAKORI_HISTORIKUS_ADAT ADD FOREIGN KEY (SZEMELYITORZS) REFERENCES SZEMELYITORZS(TSZ)
/

ALTER TABLE MUNKAKORI_HISTORIKUS_ADAT ADD FOREIGN KEY (FEOR) REFERENCES ERTEKKESZLET_ELEM(ID)
/