CREATE TABLE MEGJEGYZES
  (
    ID									INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SZEMELYITORZS			 			INT NOT NULL,
    SZOVEG			 					VARCHAR(20000)
  )
/

ALTER TABLE MEGJEGYZES ADD FOREIGN KEY (SZEMELYITORZS) REFERENCES SZEMELYITORZS(TSZ)
/