CREATE TABLE KEPZETTSEG
  (
    ID									INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SZEMELYITORZS			 			INT NOT NULL,
    TIPUS								VARCHAR(255),
    MEGNEVEZES							VARCHAR(255) NOT NULL,
    MOD_FOK								VARCHAR(255),
    EV									INT NOT NULL DEFAULT -1,
    ERVENYESSEG_VEGE_EV					INT NOT NULL DEFAULT -1,
    ERVENYESSEG_VEGE_HO					INT NOT NULL DEFAULT -1,
    ERVENYESSEG_VEGE_NAP				INT NOT NULL DEFAULT -1,
    MEGJEGYZES							VARCHAR(255)
  )
/

ALTER TABLE KEPZETTSEG ADD FOREIGN KEY (SZEMELYITORZS) REFERENCES SZEMELYITORZS(TSZ)
/