CREATE TABLE ATVETT_ESZKOZ
  (
    ID									INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SZEMELYITORZS			 			INT NOT NULL,
    MEGNEVEZES							VARCHAR(255) NOT NULL,
    MEGJEGYZES							VARCHAR(255),
    EREDETI_NEV							VARCHAR(255)
  )
/

ALTER TABLE ATVETT_ESZKOZ ADD FOREIGN KEY (SZEMELYITORZS) REFERENCES SZEMELYITORZS(TSZ)
/